version: '3.8'

services:
  db:
    image: mysql:8.0.39
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ziptie
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: ziptie_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env